// Login Flow
export const SPLASH_SCREEN = 'SPLASH_SCREEN';
export const HOME_SCREEN = 'HOME_SCREEN';
export const ONBOARDING_SCREEN = 'ONBOARDING_SCREEN';

// BOTTOM TAB STACK
export const HOME_STACK = 'HOME_STACK';
export const CATEGORY_STACK = 'CATEGORY_STACK';
export const NOTIFICATION_STACK = 'NOTIFICATION_STACK';
export const PROFILE_STACK = 'PROFILE_STACK';
export const BOTTOM_TAB = 'BOTTOM_TAB';

//CATEGORY STACK
export const CATEGORY_SCREEN = 'CATEGORY_SCREEN';
export const CATEGORY_DETAIL_SCREEN = 'CATEGORY_DETAIL_SCREEN';

//ORDER STACK
export const ORDERDETAIL_SCREEN = 'ORDERDETAIL_SCREEN';
export const CANCELRETURNDETAIL_SCREEN = 'CANCELRETURNDETAIL_SCREEN';

//MAINSTACK SCREEN
export const PRODUCT_DETAIL_VIEW_SCREEN = 'PRODUCT_DETAIL_VIEW_SCREEN';
export const MY_ADDRESSES = 'MY_ADDRESSES';
export const DELIEVERY_ADDRESS = 'DELIEVERY_ADDRESS';
export const BILLING_ADDRESS = 'BILLING_ADDRESS';
export const ADD_NEW_ADDRESS = 'ADD_NEW_ADDRESS';
export const CURRENCY_SCREEN = 'CURRENCY_SCREEN';
export const NOTIFICATION_SCREEN = 'NOTIFICATION_SCREEN';
export const SELL_WITH_US_SCREEN = 'SELL_WITH_US_SCREEN';
export const PRIVACY_POLICY_SCREEN = 'PRIVACY_POLICY_SCREEN';
export const REFUND_POLICY_SCREEN = 'REFUND_POLICY_SCREEN';
export const SHIPPING_POLICY_SCREEN = 'SHIPPING_POLICY_SCREEN';
export const TERMS_AND_CONDITION_SCREEN = 'TERMS_AND_CONDITION_SCREEN';
export const CONTACT_US_SCREEN = 'CONTACT_US_SCREEN';
export const MY_REVIEW_SCREEN = 'MY_REVIEW_SCREEN';
export const MY_QUESTION_ANSWER_SCREEN = 'MY_QUESTION_ANSWER_SCREEN';
export const EDIT_PROFILE_SCREEN = 'EDIT_PROFILE_SCREEN';
export const WISHLIST_SCREEN = 'WISHLIST_SCREEN';
export const ORDER_SCREEN = 'ORDER_SCREEN';
export const FORGET_PASSWORD_SCREEN = 'FORGET_PASSWORD_SCREEN';
export const FORGET_PASSWORD_OTP_SCREEN = 'FORGET_PASSWORD_OTP_SCREEN';
export const SUCCESS_SCREEN = 'SUCCESS_SCREEN';
export const SUCCESS_SCREEN_VERIFY_NUMBER = 'SUCCESS_SCREEN_VERIFY_NUMBER';
export const MOBILE_OTP_SCREEN = 'MOBILE_OTP_SCREEN';
export const QUESTION_DETAIL_VIEW = 'QUESTION_DETAIL_VIEW';
export const YOUR_CART_SCREEN = 'YOUR_CART_SCREEN';
export const ORDER_SUMMARY_SCREEN = 'ORDER_SUMMARY_SCREEN';
export const FILTER = 'FILTER';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const VERIFY_NUMBER_EDIT_PROFILE = 'VERIFY_NUMBER_EDIT_PROFILE';
//PROFILESTACK SCREEN
export const PROFILE_SCREEN = 'PROFILE_SCREEN';

//LOGIN SCREEN
export const LOGIN_SCREEN = 'LOGIN_SCREEN';
export const CREATE_NEW_ACCOUNT = 'CREATE_NEW_ACCOUNT';
export const VERIFY_MOBILE_NUMBER = 'VERIFY_MOBILE_NUMBER';
export const VERIFY_EMAIL = 'VERIFY_EMAIL';

//Payment
export const PAYMENT_SCREEN = 'PAYMENT_SCREEN';
export const PAYMENT_SUCCESS = 'PAYMENT_SUCCESS';
