// Login Flow
export const SPLASH_SCREEN = 'SPLASH_SCREEN';
export const HOME_SCREEN = 'HOME_SCREEN';

// BOTTOM TAB STACK
export const HOME_STACK = 'HOME_STACK';
export const CATEGORY_STACK = 'CATEGORY_STACK';
export const NOTIFICATION_STACK = 'NOTIFICATION_STACK';
export const PROFILE_STACK = 'PROFILE_STACK';
export const BOTTOM_TAB = 'BOTTOM_TAB';

//CATEGORY STACK
export const CATEGORY_SCREEN = 'CATEGORY_SCREEN';
export const CATEGORY_DETAIL_SCREEN = 'CATEGORY_DETAIL_SCREEN';
