// Login Flow
export const SPLASH_SCREEN = 'SPLASH_SCREEN';
export const HOME_SCREEN = 'HOME_SCREEN';

// BOTTOM TAB STACK
export const HOME_STACK = 'HOME_STACK';
export const CATEGORY_STACK = 'CATEGORY_STACK';
export const NOTIFICATION_STACK = 'NOTIFICATION_STACK';
export const PROFILE_STACK = 'PROFILE_STACK';
export const BOTTOM_TAB = 'BOTTOM_TAB';

//CATEGORY STACK
export const CATEGORY_SCREEN = 'CATEGORY_SCREEN';
export const CATEGORY_DETAIL_SCREEN = 'CATEGORY_DETAIL_SCREEN';

//MAINSTACK SCREEN
export const Product_Detail_View_Screen = 'Product_Detail_View_Screen';
export const MY_ADDRESSES = 'MY_ADDRESSES';
export const DELIEVERY_ADDRESS = 'DELIEVERY_ADDRESS';
export const BILLING_ADDRESS = 'BILLING_ADDRESS';
export const ADD_NEW_ADDRESS = 'ADD_NEW_ADDRESS';
export const CURRENCY_SCREEN = 'CURRENCY_SCREEN';
export const NOTIFICATION_SCREEN = 'NOTIFICATION_SCREEN';
export const SELL_WITH_US_SCREEN = 'SELL_WITH_US_SCREEN';
export const PRIVACY_POLICY_SCREEN = 'PRIVACY_POLICY_SCREEN';
export const REFUND_POLICY_SCREEN = 'REFUND_POLICY_SCREEN';
export const SHIPPING_POLICY_SCREEN = 'SHIPPING_POLICY_SCREEN';
export const TERMS_AND_CONDITION_SCREEN = 'TERMS_AND_CONDITION_SCREEN';
export const CONTACT_US_SCREEN = 'CONTACT_US_SCREEN';
export const MY_REVIEW_SCREEN = 'MY_REVIEW_SCREEN';
export const MY_QUESTION_ANSWER_SCREEN = 'MY_QUESTION_ANSWER_SCREEN';
export const EDIT_PROFILE_SCREEN = 'EDIT_PROFILE_SCREEN';
export const WISHLIST_SCREEN = 'WISHLIST_SCREEN';
export const ORDER_SCREEN = 'ORDER_SCREEN';

//PROFILESTACK SCREEN
export const PROFILE_SCREEN = 'PROFILE_SCREEN';

//ORDERSTACK SCREEN
