// export const globalDefaultImage = require('../../src/assets/images/NoImages.png')

const GlobalImage = {
  coffeeNetworkImage:
    'https://res.cloudinary.com/dawhb2mne/image/upload/v1698040599/haridwar-mart-bru-coffee_xkr9a1.png',
  categoryImg: require('../../src/assets/images/categoryimg.png'),
  loginImage: require('../../src/assets/images/login_img.png'),
  otpMobileNumberImage: require('../../src/assets/images/mobile_otp.png'),
  otpEmailImage: require('../../src/assets/images/email_verify.png'),
  coffieImage: require('../../src/assets/images/coffee.png'),
  detolImage: require('../../src/assets/images/dettol.png'),
  offerImage: require('../../src/assets/images/rectangle.png'),
  bannerOfferImage: require('../../src/assets/images/BannerOfferImage.png'),
  bannerOfferImage2: require('../../src/assets/images/BannerOfferImage2.png'),
  bannerOfferImage3: require('../../src/assets/images/OralBImage.png'),
  bannerOfferImage4: require('../../src/assets/images/NivaImage.png'),
  manFaceCreamImage: require('../../src/assets/images/ManFairCream.png'),
  vanishImage: require('../../src/assets/images/vanish.png'),
  profileImage: require('../../src/assets/images/avatar.png'),
  indiaFlag: require('../../src/assets/images/india.png'),
  ukFlag: require('../../src/assets/images/uk.png'),
  ring: require('../../src/assets/images/Ring.png'),
  circlePendant: require('../../src/assets/images/circlePendent.png'),
  TwoEarings: require('../../src/assets/images/twoEarings.png'),
  WhiteEarings: require('../../src/assets/images/WhiteEarings.png'),
  Ring2: require('../../src/assets/images/Ring2.png'),
  Ring3: require('../../src/assets/images/Ring3.png'),
  Ring4: require('../../src/assets/images/Ring4.png'),
  Ring5: require('../../src/assets/images/Ring5.png'),
  Ring6: require('../../src/assets/images/Ring6.png'),
  Set1: require('../../src/assets/images/Banner1.png'),
  Set2: require('../../src/assets/images/Banner2.png'),
  Set3: require('../../src/assets/images/Banner3.png'),
  Brand1: require('../../src/assets/images/Brand1.png'),
  Brand2: require('../../src/assets/images/Brand2.png'),
  Brand3: require('../../src/assets/images/Brand3.png'),
  Brand4: require('../../src/assets/images/Brand4.png'),
  Goldenearings: require('../../src/assets/images/Goldenearings.png'),
  GoldenPendent: require('../../src/assets/images/GoldenPendent.png'),
  GoldenRings: require('../../src/assets/images/GoldenRings.png'),
  productDetail: require('../../src/assets/images/productDetail.png'),
};

export {GlobalImage};
